# Generated by packages/cli/scripts/homebrew.ts in the AI Inbx monorepo.
class Aiinbx < Formula
  desc "Command-line interface for the AI Inbx email API"
  homepage "https://aiinbx.com"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.4.0/aiinbx-darwin-arm64.tar.gz"
      sha256 "6fa472427276eefd061723e8a36c440d7136c885cdc790f54989409a186df8ca"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.4.0/aiinbx-darwin-x64.tar.gz"
      sha256 "cc8922c4c84b9ae2a343abbd17bfdcae65392513909b62dc96baa003d76da380"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.4.0/aiinbx-linux-arm64.tar.gz"
      sha256 "c57c793d9060e456c05bd8deb5c7370ae8e56d162b341952426dc73745d8b06a"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.4.0/aiinbx-linux-x64.tar.gz"
      sha256 "b84040a7e2caffee928c090cb97f5952d69227a23c040b9c3ac38cd40eeb3c11"
    end
  end

  def install
    bin.install "aiinbx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aiinbx --version")
  end
end
