# Generated by packages/cli/scripts/homebrew.ts in the AI Inbx monorepo.
class Aiinbx < Formula
  desc "Command-line interface for the AI Inbx email API"
  homepage "https://aiinbx.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.2.0/aiinbx-darwin-arm64.tar.gz"
      sha256 "f5b646017fcc0f340860a1ab9eb4545c9dc4bd065c396b0676fb663b857286da"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.2.0/aiinbx-darwin-x64.tar.gz"
      sha256 "92f22591420bede94e7ec2439daf2393d2060f2bc6300eccc9937187ca20ed15"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.2.0/aiinbx-linux-arm64.tar.gz"
      sha256 "ad0e4b27bef10f040cddf6c5a3fd528338b0d697c9ea3c6bd9a9cba334a28134"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.2.0/aiinbx-linux-x64.tar.gz"
      sha256 "0b5db063947db2c1729544e300ddd55119097e4402038240ec1c8cda5fb1a763"
    end
  end

  def install
    bin.install "aiinbx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aiinbx --version")
  end
end
