# Generated by packages/cli/scripts/homebrew.ts in the AI Inbx monorepo.
class Aiinbx < Formula
  desc "Command-line interface for the AI Inbx email API"
  homepage "https://aiinbx.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.1.0/aiinbx-darwin-arm64.tar.gz"
      sha256 "dc1f21ab37101431c9cf22929adca801c1c0b27d5cfb3bbb6b565a6a36ca9a0e"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.1.0/aiinbx-darwin-x64.tar.gz"
      sha256 "e973aaaf63f2821759038dbaae056701a9431fdc31ec16f25328717ef5f0657c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aiinbx/cli/releases/download/v0.1.0/aiinbx-linux-arm64.tar.gz"
      sha256 "7f9d5ad11c81908afe2219ed2cb1c09e3901cc950c70638129cf94cfa639d0f6"
    end
    on_intel do
      url "https://github.com/aiinbx/cli/releases/download/v0.1.0/aiinbx-linux-x64.tar.gz"
      sha256 "fa27bb74f56f866baa32310e879660bb804703bf09d5d804938ff06b92178c47"
    end
  end

  def install
    bin.install "aiinbx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aiinbx --version")
  end
end
